### PR TITLE
Runtime 43

### LINKED ISSUE #10: Unsupported runtime (42)
Flatpak reports that this is now using an unsupported runtime:

```
Info: runtime org.gnome.Platform branch 42 is end-of-life, with reason:
   The GNOME 42 runtime is no longer supported as of March 21, 2023. Please ask your application developer to migrate to a supported platform.
Info: applications using this runtime:
   com.endlessm.photos
```

It looks like #9  would have fixed this, though runtime 44 is now the current stable.

### PR DESCRIPTION
**Pull request by bbhtt**
Trying runtime 43...

The python manifest is now generated with `flatpak-pip-generator`, that updates the dependencies and individual module requirements and cleans up the indentation mess.

Closes https://github.com/flathub/com.endlessm.photos/issues/10

### CODE REVIEW

**Comment by bbhtt** [comment]
> Started [test build 113090](https://buildbot.flathub.org/#/builders/32/builds/113090)

```
  INFO: unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  Traceback (most recent call last):
    File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 363, in <module>
      main()
    File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 345, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/usr/lib/python3.10/site-packages/pip/_vendor/pep517/in_process/_in_process.py", line 164, in prepare_metadata_for_build_wheel
      return hook(metadata_directory, config_settings)
    File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 377, in prepare_metadata_for_build_wheel
      self.run_setup()
    File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 482, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/usr/lib/python3.10/site-packages/setuptools/build_meta.py", line 335, in run_setup
      exec(code, locals())
    File "<string>", line 494, in <module>
    File "<string>", line 486, in setup_package
    File "/usr/lib/python3.10/site-packages/setuptools/__init__.py", line 87, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
      return run_commands(dist)
    File "/usr/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
      dist.run_commands()
    File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 973, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.10/site-packages/setuptools/dist.py", line 1217, in run_command
      super().run_command(command)
    File "/usr/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 992, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.10/site-packages/setuptools/command/dist_info.py", line 96, in run
      self.egg_info.run()
    File "/tmp/pip-install-_g3rg1g1/numpy_77ea1b650ee54eb69e4996ca9a1b66f6/numpy/distutils/command/egg_info.py", line 25, in run
      _egg_info.run(self)
    File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 308, in run
      self.find_sources()
    File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 316, in find_sources
      mm.run()
    File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 560, in run
      self.add_defaults()
    File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 597, in add_defaults
      sdist.add_defaults(self)
    File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 107, in add_defaults
      self._add_defaults_build_sub_commands()
    File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 127, in _add_defaults_build_sub_commands
      self.filelist.extend(chain.from_iterable(files))
    File "/usr/lib/python3.10/site-packages/setuptools/command/egg_info.py", line 503, in extend
      self.files.extend(filter(self._safe_path, paths))
    File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 126, in <genexpr>
      files = (c.get_source_files() for c in cmds if hasattr(c, "get_source_files"))
    File "/usr/lib/python3.10/site-packages/setuptools/command/sdist.py", line 125, in <genexpr>
      cmds = (self.get_finalized_command(c) for c in missing_cmds)
    File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 306, in get_finalized_command
      cmd_obj.ensure_finalized()
    File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 109, in ensure_finalized
      self.finalize_options()
    File "/tmp/pip-install-_g3rg1g1/numpy_77ea1b650ee54eb69e4996ca9a1b66f6/numpy/distutils/command/config_compiler.py", line 69, in finalize_options
      v = getattr(c, a)
    File "/usr/lib/python3.10/site-packages/Cython/Distutils/old_build_ext.py", line 157, in __getattr__
      return _build_ext.build_ext.__getattr__(self, name)
    File "/usr/lib/python3.10/site-packages/setuptools/_distutils/cmd.py", line 105, in __getattr__
      raise AttributeError(attr)
  AttributeError: fcompiler. Did you mean: 'compiler'?
  error: subprocess-exited-with-error
```

https://github.com/pypa/setuptools/issues/3549

I don't think it is possible to make it use an earlier version of setuptools if I include it in the manifest (it skips the build because it finds setuptools from the runtime first) and it doesn't sound a good idea to have two different versions of setuptools in parallel.

Making this a draft until above issue is resolved.

**Comment by bbhtt** [comment]
> Build [113246 failed](https://buildbot.flathub.org/#/builders/32/builds/113246)

ninja-python is trying to download the ninja source and failing: https://github.com/scikit-build/ninja-python-distributions/issues/127

I'll pin scipy to an earlier version not depending on mesonpy.

**Comment by bbhtt** [comment]
dbus-pyton is also pinned to 1.2.18 since it also depends on mesonpy thus ninja-python

**Comment by bbhtt** [comment]
> Build [113462 successful](https://buildbot.flathub.org/#/builders/32/builds/113462) To test this build, install it from the testing repository:
> 
> ```
> flatpak install --user https://dl.flathub.org/build-repo/111064/com.endlessm.photos.flatpakref
> ```

https://github.com/endlessm/eos-photos/issues/330

**Comment by bbhtt** [comment]
Works now. cc @wjt @GeorgesStavracas

**Comment by wjt** [comment]
Thanks for this! I updated this with your patches plus a couple more from https://github.com/endlessm/eos-photos/pull/331.

**Pull request merged**
